swagger: '2.0'
info:
  version: '1.0'
  title: "progettois2 "
  description: Our API allow users to fetch many informations about their gym and their progresses 
host: se2-movies.herokuapp.com
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /sotrico:
    post:
      description: >-
        You can add a user log using this method
      summary: Create a new log
      consumes:
      - application/json
      produces:
      - application/json       
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/postStorico'
      responses:
        200:
          description: Successful Response
          schema:
            $ref: '#/definitions/error200'
        400:
          description: The request has at least one invalid parameter
          schema:
            $ref: '#/definitions/error422'

    delete:
      summary: Delete history by timestamp.
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/data_to_del'
            
        description: >
          You can use this method to delete an history log about a specific user.
      responses:
        200:
          description: Successful Response
          schema:
            $ref: '#/definitions/error200'
        404:
          description: The required id was not found
          schema:
            $ref: '#/definitions/error404'

    put:
      summary: Modify an history by id, timestamp and exercises.
      description: >-
        If you wrong a log you may use this method to update it.
      consumes:
      - application/json
      produces:
      - application/json  
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/postStorico'
      responses:
        200:
          description: Successful Response
          schema:
            $ref: '#/definitions/error200'
        422:
          description: The json in the request contains some unrequired fields
          schema:
            $ref: '#/definitions/error422'
        404:
          description: The required id was not found
          schema:
            $ref: '#/definitions/error404'

  /storico/{id}/{timestamp_start}/{timestamp_stop}:
    get:
      summary: Returns a user history by ID.
      parameters:
      - name: id
        in: path
        required: true
        description: The id of the required user
        type: integer
        format: int64
        minimum: 1
      - name: timestamp_start
        in: path
        required: true
        description: The timestamp of the initial temporal gap
        type: integer
        format: int64
        minimum: 1
      - name: timestamp_stop
        in: path
        required: true
        description: The timestamp of the final temporal gap
        type: integer
        format: int64
        minimum: 1
      responses: 
        200:
          description: Successful Response
          schema:
            $ref: '#/definitions/storico'
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/error404'
        422:
          description: Malformed Input
          schema:
            $ref: '#/definitions/error422'

definitions:
  storico:
    type: array
    items:
      type: object
      properties:
        timestamp: 
          type: integer
        esercizi:
          type: array
          items: 
            type: string
        ripetizioni:
          type: array
          items: 
            type: integer
      example:
        timestamp: 1575849599
        esercizi:
        - addominali
        - piegamenti
        - pesi
        ripetizioni:
        - 10
        - 20
        - 30

  postStorico:
    type: object
    properties:
      id:
        type: integer
      timestamp: 
        type: integer
      esercizi:
        type: array
        items:
          type: string
      ripetizioni:
        type: array
        items:
          type: integer
    example:
      id: 4
      timestamp: 1576022399
      esercizi:
      - addominali
      - piegamenti
      - squat
      ripetizioni:
      - 20
      - 50
      - 1
      
  data_to_del:
    type: object
    properties:
      id:
        type: integer
      data_to_del:
        type: integer
    example:
      id: 1
      data_to_del: 1575935999

  error200:
    title: success
    type: object
    properties:
      success:
        type: string
        description: Type of success
    example:
      success: Added 3 exericises

  error404:
    title: error
    type: object
    properties:
      error: 
        type: string
        description: type of error
    example: 
      error: Storico Not found
  error422:
    title: error
    type: object
    properties:
      error: 
        type: string
        description: type of error
    example: 
      error: Error. id or dates are INVALID
      
